services:
  - type: web
    name: cfdi-shield-demo
    env: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: APP_NAME
        value: CFDI Shield
      - key: APP_VERSION
        value: "1.0"
      - key: LOCAL_MODE
        value: "False"
      - key: ENABLE_SAT_VALIDATION
        value: "True"
      - key: DEBUG
        value: "False"
      - key: ENABLE_REGISTRATION
        value: "True"
      - key: ENABLE_BETA_MODE
        value: "True"
      - key: BETA_ACCESS_CODE
        sync: false
      - key: APP_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cfdi-shield-db
          property: connectionString

databases:
  - name: cfdi-shield-db
    plan: free
