from __future__ import annotations


DATE_MATCH_SCORE_POINTS = 20
RFC_MATCH_SCORE_POINTS = 25
SUPPLIER_NAME_MATCH_SCORE_POINTS = 25
SUPPLIER_PARTIAL_MATCH_SCORE_POINTS = 20

CONCILIADO_THRESHOLD = 80
POSIBLE_THRESHOLD = 50

MATCH_STATUS_CONCILIADO = "CONCILIADO"
MATCH_STATUS_POSIBLE = "POSIBLE"
MATCH_STATUS_PENDIENTE = "PENDIENTE"
